---
- name: Create NiFi group
  group:
    name: "{{ nifi_group }}"
    state: "present"
    system: "yes"

- name: Create NiFi user
  user:
    name: "{{ nifi_user }}"
    groups: "{{ nifi_group }}"
    append: "yes"
    state: "present"
    create_home: "no"
    system: "yes"

- name: Create directories
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
  with_items:
    - "{{ nifi_config_dirs.install }}"
    - "{{ nifi_config_dirs.run }}"
    - "{{ nifi_config_dirs.logs }}"

- name: Set NiFi home
  lineinfile:
    path: "/etc/environment"
    line: "export NIFI_HOME={{ nifi_config_dirs.home }}"
    create: "yes"
